Repository artefactual/archivematica, pull requests merged in 2018-09, with the labels that each got.

#1248 Adjust async poll timeout
  src/archivematicaCommon/lib/storageService.py
Labels: OCUL: AM-Dataverse

#1244 Enable removal of duplicate files from uploadDIP
  src/MCPClient/lib/clientScripts/store_aip.py
Labels: Status: in progress

#1254 MCPClient: fix string formatting in normalize.py
  src/MCPClient/lib/clientScripts/normalize.py
Labels: Type: bug

#1242 Create a Dataverse transfer type
  src/MCPClient/lib/archivematicaClientModules
  src/MCPClient/lib/clientScripts/convert_dataverse_structure.py
  src/MCPClient/lib/clientScripts/create_mets_dataverse_v2.py
  src/MCPClient/lib/clientScripts/create_mets_v2.py
  src/MCPClient/lib/clientScripts/parse_dataverse_mets.py
  src/MCPClient/requirements/base.txt
  src/MCPClient/tests/fixtures/dataverse/dataverse_sources/metadata/api_demo.dataverse.org.doi.10.5072.4.json
  src/MCPClient/tests/fixtures/dataverse/dataverse_sources/metadata/api_demo.dataverse.org.doi.10.5072.5.json
  src/MCPClient/tests/fixtures/dataverse/dataverse_sources/metadata/api_demo.dataverse.org.doi.10.5072.6.json
  src/MCPClient/tests/fixtures/dataverse/dataverse_sources/metadata/api_demo.dataverse.org.doi.10.5072.7.json
  src/MCPClient/tests/fixtures/dataverse/dataverse_sources/metadata/api_demo.dataverse.org.doi.10.5072.8.json
  src/MCPClient/tests/fixtures/dataverse/dataverse_sources/metadata/web_ui_demo.dataverse.org.doi.10.5072.1.json
  src/MCPClient/tests/fixtures/dataverse/dataverse_sources/metadata/web_ui_demo.dataverse.org.doi.10.5072.2.json
  src/MCPClient/tests/fixtures/dataverse/dataverse_sources/metadata/web_ui_demo.dataverse.org.doi.10.5072.3.json
  src/MCPClient/tests/test_create_dataverse_mets.py
  src/MCPServer/lib/archivematicaMCP.py
  src/MCPServer/lib/package.py
  src/dashboard/frontend/transfer-browser/app/front_page/content.html
  src/dashboard/src/components/filesystem_ajax/views.py
  src/dashboard/src/main/migrations/0061_create_dataverse_transfer_type.py
Labels: Status: in progress
