Repository artefactual/archivematica, pull requests merged in 2018-08, with the labels that each got.

#1153 Dashboard: fix review_matches to avoid KeyError
  src/dashboard/src/components/ingest/pair_matcher.py
Labels: RAC, Type: bug

#1234 Enhance search enabled configuration
  src/MCPClient/install/README.md
  src/MCPClient/lib/clientScripts/elastic_search_index_process_transfer.py
  src/MCPClient/lib/clientScripts/index_aip.py
  src/MCPClient/lib/clientScripts/post_store_aip_hook.py
  src/MCPClient/lib/clientScripts/remove_aip_files_from_index.py
  src/MCPClient/lib/settings/common.py
  src/MCPServer/install/README.md
  src/MCPServer/lib/settings/common.py
  src/archivematicaCommon/lib/abilities.py
  src/archivematicaCommon/lib/appconfig.py
  src/archivematicaCommon/tests/test_appconfig.py
  src/dashboard/install/README.md
  src/dashboard/src/components/archival_storage/views.py
  src/dashboard/src/components/backlog/views.py
  src/dashboard/src/main/context_processors.py
  src/dashboard/src/settings/base.py
  src/dashboard/src/templates/administration/general.html
  src/dashboard/src/templates/appraisal/appraisal.html
  src/dashboard/src/templates/archival_storage/list.html
  src/dashboard/src/templates/backlog/backlog.html
  src/dashboard/src/templates/ingest/grid.html
  src/dashboard/src/templates/layout.html
Labels: ES-upgrade, Request: discussion, Type: enhancement

#1243 Enable removal of duplicate files from uploadDIP watched directory
  src/MCPClient/lib/clientScripts/storeAIP.py
Labels: Status: in progress
