Repository artefactual/archivematica, pull requests merged in 2018-03, with the labels that each got.

#979 MCPClient: stop pickling custom exception
  src/MCPClient/lib/archivematicaClient.py
Labels: bug

#981 archivematicaCommon: stop accessing content attribute of exception
  src/archivematicaCommon/lib/storageService.py
Labels: bug

#984 MCPClient: stop documenting empty dirs in metadata/
  src/MCPClient/lib/clientScripts/archivematicaCreateMETS2.py
Labels: bug

#985 CHANGELOG: add link to release notes
  CHANGELOG.md
Labels: documentation

#991 Explicitly handle Archivematica Archivesspace cfg
  src/dashboard/src/components/access/views.py
  src/dashboard/src/components/ingest/views_as.py
Labels: nice to have

#990 Reenables the preview capability of appraisal tab
  src/dashboard/frontend/appraisal-tab/app/preview/preview.controller.js
  src/dashboard/frontend/appraisal-tab/app/preview/preview.html
  src/dashboard/src/components/filesystem_ajax/urls.py
  src/dashboard/src/components/filesystem_ajax/views.py
  src/dashboard/src/components/helpers.py
Labels: bug

#1024 MCPClient: change verify_AIP to verify_aip
  src/MCPClient/lib/archivematicaClientModules
Labels: bug
