Repository artefactual/archivematica, pull requests merged in 2018-05, with the labels that each got.

#1081 Catch name error manual normalization
  src/MCPClient/lib/clientScripts/manualNormalizationCreateMetadataAndRestructure.py
  src/MCPClient/lib/clientScripts/manualNormalizationMoveAccessFilesToDIP.py
  src/archivematicaCommon/lib/fileOperations.py
Labels: bug

#1089 Fixes in CONTRIBUTING.md
  CONTRIBUTING.md
  code_review.md
Labels: documentation

#1098 Bump version to 1.7.1
  src/archivematicaCommon/lib/version.py
Labels: CUL: phase 2, Columbia University Library

#1096 MCPClient/Server: from-stdout task overrides output capturing
  src/MCPClient/lib/archivematicaClient.py
  src/MCPServer/lib/linkTaskManagerGetMicroserviceGeneratedListInStdOut.py
  src/MCPServer/lib/taskStandard.py
Labels: CUL: phase 2, Columbia University Library, bug
