Repository artefactual/archivematica, pull requests merged in 2018-07, with the labels that each got.

#1184 Dashboard: fix string formatting in __unicode__ methods
  src/dashboard/src/main/models.py
Labels: bug

#1170 storageService: add new query timeout
  src/MCPClient/install/README.md
  src/MCPClient/lib/settings/common.py
  src/archivematicaCommon/lib/storageService.py
  src/dashboard/install/README.md
  src/dashboard/src/settings/base.py
Labels: Jisc RDSS, Review

#1190 MCPClient: add indexAIP error handling
  src/MCPClient/install/README.md
  src/MCPClient/lib/clientScripts/index_aip.py
  src/MCPClient/lib/settings/common.py
  src/dashboard/src/main/migrations/0054_index_aip_silent_error_branch.py
Labels: Jisc RDSS, Review

#1193 Dashboard: set_agent_code command
  src/dashboard/src/components/administration/management/commands/set_agent_code.py
  src/dashboard/src/installer/steps.py
Labels: Jisc RDSS, Review

#1200 Add retry logic for concurrency sensitive database transactions
  src/MCPClient/lib/archivematicaClient.py
  src/MCPServer/lib/taskGroup.py
  src/archivematicaCommon/lib/databaseFunctions.py
Labels: Jisc RDSS

#1208 Fix JSON->CSV metadata conversion
  src/MCPClient/lib/clientScripts/json_metadata_to_csv.py
  src/MCPClient/tests/test_json_conversion.py
Labels: Edinburgh, Type: bug

#1213 Dashboard: disable CSRF in /api (shib only)
  src/dashboard/src/components/api/views.py
Labels: Jisc RDSS

#1209 MCPClient: job.py allow Unicode printing
  src/MCPClient/lib/job.py
  src/MCPClient/tests/test_job.py
  src/archivematicaCommon/lib/custom_handlers.py
Labels: IISH, Type: bug

#1211 Allow package create without transfer source details
  src/MCPServer/lib/package.py
  src/archivematicaCommon/lib/storageService.py
Labels: Jisc RDSS

#1216 Introduce thumbnail mode
  src/MCPClient/lib/archivematicaClientModules
  src/MCPClient/lib/clientScripts/copy_thumbnails_to_dip_directory.py
  src/MCPClient/lib/clientScripts/normalize.py
  src/MCPClient/lib/clientScripts/remove_directories.py
  src/dashboard/src/components/administration/forms.py
  src/dashboard/src/main/migrations/0055_normalize_thumbnail_mode_selection.py
Labels: Jisc RDSS

#1214 Capture any exception in index_aip to job's stderr
  src/MCPClient/lib/clientScripts/index_aip.py
Labels: Jisc RDSS

#1217 Transfer Browser: add auto_approve checkbox
  src/MCPServer/lib/RPCServer.py
  src/dashboard/frontend/transfer-browser/app/front_page/content.html
  src/dashboard/frontend/transfer-browser/app/services/transfer.service.js
  src/dashboard/src/components/api/views.py
  src/dashboard/tests/test_api_v2beta.py
Labels: IISH, Jisc RDSS

#1220 Update import for create_mets_v2
  src/MCPClient/lib/clientScripts/create_aic_mets.py
Labels: Jisc RDSS

#1224 Small fix in email_fail_report
  src/MCPClient/lib/clientScripts/email_fail_report.py
Labels: Jisc RDSS

#1225 Standardise global state in create_mets_v2
  src/MCPClient/lib/clientScripts/archivematicaCreateMETSReingest.py
  src/MCPClient/lib/clientScripts/create_aic_mets.py
  src/MCPClient/lib/clientScripts/create_mets_v2.py
  src/MCPClient/lib/clientScripts/create_processed_structmap.py
  src/MCPClient/tests/test_create_aip_mets.py
  src/MCPClient/tests/test_reingest_mets.py
  src/archivematicaCommon/lib/externals/extractMaildirAttachments.py
Labels: Jisc RDSS

#1178 Correct PREMIS:originalName for packaged objects
  src/MCPClient/lib/clientScripts/extract_contents.py
  src/archivematicaCommon/lib/archivematicaFunctions.py
  src/archivematicaCommon/lib/databaseFunctions.py
  src/archivematicaCommon/lib/fileOperations.py
  src/archivematicaCommon/tests/test_database_functions.py
  src/dashboard/src/main/models.py
Labels: IISH, Status: in progress

#1227 MCPServer: use auto_close_db
  src/MCPClient/lib/fork_runner.py
  src/MCPServer/lib/RPCServer.py
  src/MCPServer/lib/package.py
Labels: Jisc RDSS

#1229 Add 7zip copy mode
  src/dashboard/src/main/migrations/0057_7zip_no_compression.py
Labels: IISH, Status: in progress
