Repository artefactual/archivematica, pull requests merged in 2018-06, with the labels that each got.

#1115 Correct default behaviour of extract packages and adds Unicode formatted strings
  src/archivematicaCommon/lib/archivematicaFunctions.py
  src/dashboard/src/main/migrations/0052_correct_extract_packages_fallback_link.py
Labels: IISH

#1152 MCPClient: make checksum verification for re-ingest more robust
  src/MCPClient/lib/clientScripts/verify_aip.py
Labels: bug

#1160 Fix PDF normalization command output
  src/dashboard/src/requirements/base.txt
Labels: enhancement

#1165 Make installer idempotent
  src/archivematicaCommon/lib/storageService.py
  src/dashboard/src/components/administration/views.py
  src/dashboard/src/installer/steps.py
Labels: Jisc RDSS

#1142 Add site_url setting
  src/archivematicaCommon/lib/storageService.py
  src/dashboard/install/README.md
  src/dashboard/src/components/administration/forms.py
  src/dashboard/src/components/administration/views.py
  src/dashboard/src/installer/forms.py
  src/dashboard/src/installer/management/commands/install.py
  src/dashboard/src/installer/steps.py
  src/dashboard/src/installer/views.py
  src/dashboard/src/settings/base.py
  src/dashboard/src/templates/administration/general.html
Labels: Jisc RDSS

#1168 Exclude empty dublin core elements
  src/MCPClient/lib/clientScripts/parse_mets_to_db.py
Labels: Jisc RDSS

#1167 Add checks for empty transfers
  src/MCPClient/lib/clientScripts/verifyTransferCompliance.py
Labels: Jisc RDSS
